Update Chapter 1:  Bash Basics

diff --git a/Chapter 1:  Bash Basics b/Chapter 1:  Bash Basics
--- a/Chapter 1:  Bash Basics
+++ b/Chapter 1:  Bash Basics
@@ -490,4 +490,63 @@ Control Operators
 
 #! bin/bash (page 17)
 
-    
+# This script will send the sleep command to the background
+echo "Sleeping for 10 seconds"
+sleep 10 &
+
+# Creates a file
+
+echo "Creating the file test123"
+touch test123
+
+# Deletes a file
+echo "Deleting the file test123"
+rm test123
+
+  Commands that are long-running are often sent to the background to prevent scripts from running. 
+  The && operator allows us to perform an AND operation between two commands. 
+  In the following example, the file test123 will be created only if the first command is successful
+
+touch test && touch test123
+
+  The () operator allows us to group commands so they act as a single unit when we need them to redirect together. 
+
+(ls, ps)
+
+  This is generally useful when you need to redirect results from multiple commands to a stream. 
+  The ; operator allows us to run multiple commands regardless of their exit status. 
+
+ls:ps: whoami
+
+  As a result, each command is executed one after the other, as soon as the previous one finishes. 
+  The || operator allows us to chain commands toegether using an OR operation. 
+
+lzl || echo "the lzl command failed"
+
+  In this example, the echo commandwill be executed only if the first command fails. 
+
+Redirection Operators
+
+  The three standard strerams we highlighted earlier can be redirected from one program to another. 
+  Redirection is taking output from one command or script and using it as input to another script or file for writing purposes. 
+
+> 
+  redirects stdout to a file
+>> 
+  Redirects stdout to a file by appending it to the existing content
+&> OR >&
+  Redirects stdout and stderr to a file
+&>>
+  Redirects stdout and stderr to a file by appending them to the existing content
+<
+  Redirects input to a command
+<<
+  Called a here document, or heredoc, redirects multiple input lines to a command
+||
+  Redirects output of a command as input to another command
+
+  The > operator redirects the standard output stream to file.
+
+$ echo "Hello World" > output.txt
+
+  We redirect the standard output stream to a file named output.txt. (Page 19).
